[set0]
left_motor = [
	[0x38, 0],
	[0x31, 0],
	[0x30, 0],
	[0x1C, 0],
	[0x16, 0],
	[0x11, 0],
	[0x0D, 0],
	[0x08, 0],
	[0x04, 0]
]
right_motor = [
]

[set1]
left_motor = [
	[0x38, 0],
	[0x31, 0],
	[0x30, 0],
	[0x1C, 0],
	[0x16, 0],
	[0x11, 0],
	[0x0D, 0],
	[0x08, 0],
	[0x04, 0]
]
right_motor = [
]

[set2]
left_motor = [
	[0x38, 0],
	[0x31, 0],
	[0x30, 0],
	[0x1C, 0],
	[0x16, 0],
	[0x11, 0],
	[0x0D, 0],
	[0x08, 0],
	[0x04, 0]
]
right_motor = [
]

[set3]
left_motor = [
	[0x38, 0],
	[0x31, 0],
	[0x30, 0],
	[0x1C, 0],
	[0x16, 0],
	[0x11, 0],
	[0x0D, 0],
	[0x08, 0],
	[0x04, 0]
]
right_motor = [
]
